apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quizzz.fullname" . }}
  labels:
    {{- include "quizzz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quizzz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quizzz.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "quizzz.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
